apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-session-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-session-tracker
  template:
    metadata:
      labels:
        app: user-session-tracker
    spec:
      containers:
        - name: user-session-tracker
          image: user-session-tracker:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: user-session-tracker
spec:
  selector:
    app: user-session-tracker
  ports:
    - port: 8081
      targetPort: 8081
  type: LoadBalancer 