apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  SPRING_PROFILES_ACTIVE: prod
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: spring_db
  SERVICES: "dynamodb,s3,sqs,kinesis,cloudwatch"
  DEFAULT_REGION: "us-east-1"
  HMAC_SECRET: "your-secure-hmac-secret-key"  # This should be replaced with a secure key in production
  JWT_SECRET: "your-secure-jwt-secret-key"    # This should be replaced with a secure key in production
  SPRING_SECURITY_USER_NAME: admin
  SPRING_SECURITY_USER_PASSWORD: "admin"      # This should be replaced with a secure password in production
  SPRING_SECURITY_USER_ROLES: ADMIN 