apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: spring-app
spec:
  ports:
    - port: 4566
      targetPort: 4566
  selector:
    app: localstack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:1.4.0
          ports:
            - containerPort: 4566
          env:
            - name: SERVICES
              valueFrom:
                configMapKeyRef:
                  name: spring-config
                  key: SERVICES
            - name: DEFAULT_REGION
              valueFrom:
                configMapKeyRef:
                  name: spring-config
                  key: DEFAULT_REGION
            - name: DEBUG
              value: "1"
            - name: DATA_DIR
              value: "/tmp/localstack/data"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          volumeMounts:
            - name: localstack-data
              mountPath: /tmp/localstack/data
          readinessProbe:
            httpGet:
              path: /_localstack/health
              port: 4566
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /_localstack/health
              port: 4566
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: localstack-data
          emptyDir: {} 