apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: spring-app
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'spring-app'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['spring-app:8081']
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            regex: '(.*):.*'
            replacement: '$1'
      
      - job_name: 'postgres'
        static_configs:
          - targets: ['postgres:5432']
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            regex: '(.*):.*'
            replacement: '$1'
      
      - job_name: 'localstack'
        static_configs:
          - targets: ['localstack:4566']
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            regex: '(.*):.*'
            replacement: '$1' 