apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  JWT_SECRET: your-secure-jwt-secret-key
  SPRING_SECURITY_USER_PASSWORD: admin 