apiVersion: v1
kind: Service
metadata:
  name: user-session-tracker-service
  namespace: default
spec:
  selector:
    app: user-session-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer 