apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-session-tracker
  labels:
    app: user-session-tracker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-session-tracker
  template:
    metadata:
      labels:
        app: user-session-tracker
    spec:
      containers:
      - name: user-session-tracker
        image: ${ECR_REPOSITORY}:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: DYNAMODB_TABLE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: dynamodb.table
        - name: SQS_QUEUE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: sqs.queue.url
        - name: FIREHOSE_STREAM
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: firehose.stream
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: user-session-tracker
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
  selector:
    app: user-session-tracker
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  dynamodb.table: "user_sessions"
  sqs.queue.url: "user-session-queue"
  firehose.stream: "user-session-stream" 