apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-session-tracker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/user-session-tracker.git
    targetRevision: HEAD
    path: k8s
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: environment
          value: ${self:provider.stage}
        - name: image.tag
          value: ${GITHUB_SHA}
  destination:
    server: https://kubernetes.default.svc
    namespace: user-session-tracker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas 